type=item
items=bow
model=echo_of_the_valley
model.bow_pulling_0=echo_of_the_valley_pulling_0
model.bow_pulling_1=echo_of_the_valley_pulling_1
model.bow_pulling_2=echo_of_the_valley_pulling_2
components.custom_name=Echo of the Valley