name = "pollocraft"
author = "yungando"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a45a6e162a0bae31f5ec4a4469f1c13d8e70b4e585628483a4ce8aefef632ce6"

[versions]
fabric = "0.14.4"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["21w37a", "1.18", "1.18.1", "1.18.2"]
