name = "pollocraft"
author = "yungando"
version = "5.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b4a47f85f3e317019dd3c28398b5f50dffdddf872000228f7bd14728232c3060"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
