name = "pollocraft"
author = "yungando"
version = "6.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1888677178b6cbcb38001750834ac0ed7a16ffc73429674f28bd3136eebd8c77"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"

[options]
datapack-folder = "./datapacks"
