name = "pollocraft"
author = "yungando"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5f8d34fd563aaeac354562267aab550f658c2f75419c719d89106e023e6e818b"

[versions]
fabric = "0.14.4"
minecraft = "1.18.2"
