name = "pollocraft"
author = "yungando"
version = "5.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ed269e27ac9a0e2d266df107be2f100b2dff42bdafd664197a97b5aa2f57ddae"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
