name = "pollocraft"
author = "yungando"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c602e09dbdf260213f37619d80347393c7f6609fb74589bfc711c09e81711b7e"

[versions]
fabric = "0.14.4"
minecraft = "1.18.2"
