name = "pollocraft"
author = "yungando"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cefecf53be3570dac021c0636076875860a7cee3d763b2b31adb71e4229eafa3"

[versions]
fabric = "0.14.4"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["21w37a", "1.18", "1.18.1", "1.18.2"]
