name = "pollocraft"
author = "yungando"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0e4f7f788743a46bf4c07a13593a030ac82a63efdc48d7249b578f49afd5a114"

[versions]
fabric = "0.14.4"
minecraft = "1.18.2"
