name = "pollocraft"
author = "yungando"
version = "6.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ce185c7e6da762cd84df2b855cd48308fe961ae8ae6082b6f0c194ef36767a23"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"

[options]
datapack-folder = "./datapacks"
