name = "pollocraft"
author = "yungando"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9bbccb3e7f3fdb1cd406b84006c15970f3e3448f35c13a43334b4cc517fa1ab7"

[versions]
fabric = "0.14.4"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["21w37a", "1.18", "1.18.1", "1.18.2"]
