name = "pollocraft"
author = "yungando"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9b788f5805e267cef89614de9a6698d4107b102ee4250e408bc085b0996a48fe"

[versions]
fabric = "0.14.4"
minecraft = "1.18.2"
