name = "pollocraft"
author = "yungando"
version = "6.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9e1a6215ffd8a3b4bcf56da0c6453b692f1609237f55d8b435672474f0938fde"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"

[options]
datapack-folder = "./datapacks"
