name = "pollocraft"
author = "yungando"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "21cc80be2310d71aabd4c8638452612a650f295537303f9f9e4145a21a9ef604"

[versions]
fabric = "0.14.4"
minecraft = "1.18.2"
