name = "pollocraft"
author = "yungando"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4cf63b5b6ad25acf65ee03e6297819c9e69fcad4b4dae3b53bb3646b2c6b83bf"

[versions]
fabric = "0.14.4"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["21w37a", "1.18", "1.18.1", "1.18.2"]
