name = "pollocraft"
author = "yungando"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "41fef46f51991df453438ab9e0a6070f81e48cc95c2ac59ca44e675eec23cc6a"

[versions]
fabric = "0.14.4"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["21w37a", "1.18", "1.18.1", "1.18.2"]
