name = "pollocraft"
author = "yungando"
version = "5.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e31079948ab2daf5325845ed6cbff584a259e78307d7fff55be9f8720fbfa035"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
