name = "pollocraft"
author = "yungando"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b1f2e08b1d3e6ec008feaea14af4a94f3883e2150223a163bc021221c505aa2c"

[versions]
fabric = "0.14.4"
minecraft = "1.18.2"
