name = "pollocraft"
author = "yungando"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2ea317e45629dfab499d0daad84ae96606e65b898362c1fcb0598deb4a46683a"

[versions]
fabric = "0.14.4"
minecraft = "1.18.2"
