name = "pollocraft"
author = "yungando"
version = "5.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8f6e7408ebf6b8339eb56f9de0fd7e4c411575d96857210d4e32422feef91982"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
