name = "pollocraft"
author = "yungando"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "33193a1f3e8a5699e81118d78ad1479e1672e402b70da8c97bf1077b2c887beb"

[versions]
fabric = "0.14.4"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["21w37a", "1.18", "1.18.1", "1.18.2"]
