name = "pollocraft"
author = "yungando"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9805b095c93b58d2ce1230f6bc8060498ccdea430a65f1c2c663b60ce0ae894b"

[versions]
fabric = "0.14.4"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["21w37a", "1.18", "1.18.1", "1.18.2"]
