name = "pollocraft"
author = "yungando"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6931635d214692faf36bca4acd1caa1ce14662a013bc976677e0e1bfeed5c321"

[versions]
fabric = "0.14.4"
minecraft = "1.18.2"
