type=item
items=crossbow
model.crossbow=rune_crossbow
model.crossbow_pulling_0=rune_crossbow_pulling_0
model.crossbow_pulling_1=rune_crossbow_pulling_1
model.crossbow_pulling_2=rune_crossbow_pulling_2
model.crossbow_arrow=rune_crossbow_arrow
model.crossbow_firework=rune_crossbow_firework
components.custom_name=Rune Crossbow