type=item
items=crossbow
texture.crossbow=rune_crossbow
texture.crossbow_pulling_0=rune_crossbow_pulling_0
texture.crossbow_pulling_1=rune_crossbow_pulling_1
texture.crossbow_pulling_2=rune_crossbow_pulling_2
texture.crossbow_arrow=rune_crossbow_arrow
texture.crossbow_firework=rune_crossbow_firework
components.custom_name=Rune Crossbow