type=item
items=crossbow
model=harp_crossbow
model.crossbow_pulling_0=harp_crossbow_pulling_0
model.crossbow_pulling_1=harp_crossbow_pulling_1
model.crossbow_pulling_2=harp_crossbow_pulling_2
model.crossbow_arrow=harp_crossbow_arrow
model.crossbow_firework=harp_crossbow_firework
components.custom_name=Harp Crossbow