type=item
items=crossbow
model.crossbow=shadow_crossbow
model.crossbow_pulling_0=shadow_crossbow_pulling_0
model.crossbow_pulling_1=shadow_crossbow_pulling_1
model.crossbow_pulling_2=shadow_crossbow_pulling_2
model.crossbow_arrow=shadow_crossbow_arrow
model.crossbow_firework=shadow_crossbow_firework
components.custom_name=Shadow Crossbow