type=item
items=crossbow
texture.crossbow=shadow_crossbow
texture.crossbow_pulling_0=shadow_crossbow_pulling_0
texture.crossbow_pulling_1=shadow_crossbow_pulling_1
texture.crossbow_pulling_2=shadow_crossbow_pulling_2
texture.crossbow_arrow=shadow_crossbow_arrow
texture.crossbow_firework=shadow_crossbow_firework
components.custom_name=Shadow Crossbow