name = "Complementery Shaders"
filename = "ComplementaryShaders_v4.5.zip"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3826/772/ComplementaryShaders_v4.5.zip"
hash-format = "sha1"
hash = "0ede9d4b83340e17ad6b773703746696b107adf7"

[update]
[update.curseforge]
file-id = 3826772
project-id = 385587
