name = "Complementery Shaders"
filename = "ComplementaryShaders_v4.4.zip"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3685/89/ComplementaryShaders_v4.4.zip"
hash-format = "sha1"
hash = "00E28C19AC1EE7AC886D9930D4A73E674E564D82"

[update]
[update.curseforge]
file-id = 368589
project-id = 385587
